# Obter todos
GET http://localhost:8080/api/categorias

### Obter por id
GET http://localhost:8080/api/categorias/1

### Adicionar 1
POST http://localhost:8080/api/categorias
Content-Type: application/json

{
    "nome" : "Celular",
    "descricao" : "Categoria de celular"
}

### Adicionar 2
POST http://localhost:8080/api/categorias
Content-Type: application/json

{
    "nome" : "Eletrônicos",
    "descricao" : "Categoria de eletrônicos"
}

### Atualizar
PUT http://localhost:8080/api/categorias/1
Content-Type: application/json

{
    "nome": "Notebook",
    "descricao": "Categoria de notebook",
    "produto": [
        { "id": 1 }
    ]
}

### Deletar
DELETE http://localhost:8080/api/categorias/2
