### Obter todos
GET http://localhost:8080/api/enderecos

### Obter por id
GET http://localhost:8080/api/enderecos/2

### Adicionar
POST http://localhost:8080/api/enderecos
Content-Type: application/json

{
	"cep" : "cep_teste5",
	"rua" : "rua_teste5",
	"numero" : 555,
	"bairro" : "bairro_teste5",
	"cidade" : "cidade_teste5",
	"estador" : "estador_teste5",
	"complemento" : "endereco do cliente 2"
}

### Atualizar
PUT http://localhost:8080/api/enderecos/2
Content-Type: application/json

{
	"cep" : "cep_teste2",
	"rua" : "rua_teste2",
	"numero" : 22222,
	"bairro" : "bairro_teste2",
	"cidade" : "cidade_teste2",
	"complemento" : "endereco do cliente 1"
}

### Deletar
DELETE http://localhost:8080/api/enderecos/3
