### Obter todos
GET http://localhost:8080/api/endereco

### Obter por id
GET http://localhost:8080/api/endereco/2

### Adicionar
POST http://localhost:8080/api/endereco
Content-Type: application/json

{
	"cep" : "cep_teste",
	"rua" : "rua_teste",
	"numero" : 123,
	"bairro" : "bairro_teste",
	"cidade" : "cidade_teste",
	"complemento" : "PARA DELETAR"
}

### Atualizar
PUT http://localhost:8080/api/endereco/1
Content-Type: application/json

{
	"cep" : "cep_teste_atualizado",
	"rua" : "rua_teste",
	"numero" : 123,
	"bairro" : "bairro_teste",
	"cidade" : "cidade_teste",
	"complemento" : "complemento_teste"
}

### Deletar
DELETE http://localhost:8080/api/endereco/2
