### Obter todos
GET http://localhost:8080/api/produtos

### Obter por id
GET http://localhost:8080/api/produtos/1

### Adicionar 1
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
    "dataCadastro": "2025-09-16T20:00:00.000+00:00",
    "nome": "Acer Nitro 5",
    "observacao": "Core i5, RAM 8GB, Nvidia GeForce GTX 1050",
    "quantidadeEstoque": 5,
    "valor": 3700.0
}

### Adicionar 2
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
    "dataCadastro" : "2025-09-16T20:00:00",
    "nome" : "Nokia",
    "observacao" : "Tijoção",
    "quantidadeEstoque" : 1,
    "valor" : 100.00
}

### Atualizar
PUT http://localhost:8080/api/produtos/1
Content-Type: application/json

{
    "dataCadastro": "2025-09-16T20:00:00.000+00:00",
    "nome": "Acer Nitro 5",
    "observacao": "Core i5, RAM 8GB, Nvidia GeForce GTX 1050",
    "quantidadeEstoque": 5,
    "valor": 3700.0,
    "categoria": [
        { "id": 1 }
    ]
}

### Deletar
DELETE http://localhost:8080/api/produtos/3
